# INSTALL LIBRARY 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# ARRAY OPERATIONS

In [2]:
import numpy as np

In [3]:
np.version.version

'1.21.5'

# CREATING 1D ARRAY 

In [4]:
first_array = np.array([6,5,4,3,2,1])

In [5]:
print(first_array)

[6 5 4 3 2 1]


# TWO DIMENSIONAL ARRAY 

In [6]:
second_array = np.array([(2,3,4,5),(6,7,8,9)])

In [7]:
print(second_array)

[[2 3 4 5]
 [6 7 8 9]]


# THREE DIMENSIONAL ARRAY

In [8]:
third_array  = np.array([[(17,18,19),(20,21,22),(23,24,25)]])

In [9]:
print(third_array)

[[[17 18 19]
  [20 21 22]
  [23 24 25]]]


# CREATING ARRAY WITH ZEROS

In [20]:
zero_array = np.zeros((100,100))

In [21]:
print(zero_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
one_array = np.ones((50,50))

In [24]:
print(one_array)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


# Linspace

In [25]:
spaced_num = np.linspace(0,20,50)

In [26]:
print(spaced_num)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [28]:
my_arry = np.array([1,2,3])

In [31]:
print(my_arry)

[1 2 3]


In [33]:
arr_ones = np.ones((2,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [34]:
my_matrix = np.array([(11,17,19),(23,25,27)])

In [35]:
print(my_matrix)

[[11 17 19]
 [23 25 27]]


# TRANSPOSE

In [36]:
matrix_transpose = np.transpose(my_matrix)

In [38]:
print(matrix_transpose)

[[11 23]
 [17 25]
 [19 27]]


In [39]:
matrix_transpose.ravel()

array([11, 23, 17, 25, 19, 27])

# shapes

In [46]:
my_arry.reshape(3,1)

array([[1],
       [2],
       [3]])

In [52]:
arr_ones.reshape(4,1)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [55]:
matrix_transpose.reshape(6,1)

array([[11],
       [23],
       [17],
       [25],
       [19],
       [27]])

# resize

In [59]:
arr_ones.resize((4,1))

In [60]:
print(arr_ones)

[[1.]
 [1.]
 [1.]
 [1.]]


In [61]:
np.random.random((3,3))

array([[0.04784419, 0.98725456, 0.8658796 ],
       [0.50192385, 0.97238752, 0.48619124],
       [0.24856123, 0.39590855, 0.88161863]])